# Run workflow using API

In [1]:
from pathlib import Path

from rich import print as pprint

In [2]:
import logging

logging.basicConfig(level=logging.WARNING)
# Set to WARNING to see only warnings
# Set to INFO to see sparql queries
# Set to DEBUG to see raw results

logging.getLogger("distributed").setLevel(logging.ERROR)

## Setup session directory

In this directory files like structure files are stored and a DuckDB database for meta data.

In [3]:
session_dir = Path("session1")
session_dir

PosixPath('session1')

## Search Uniprot for structures

In [5]:
from protein_quest.uniprot import Query

from protein_detective.workflow import search_structures_in_uniprot

In [6]:
query = Query(
    taxon_id="9606",
    reviewed=True,
    subcellular_location_uniprot="nucleus",
    subcellular_location_go=["GO:0005634"],  # Cellular component - Nucleus
    molecular_function_go=["GO:0003677"],  # Molecular function - DNA binding
)

In [7]:
nr_uniprot, nr_pdbe, nr_pdb_uniprot, nr_af = search_structures_in_uniprot(query, session_dir, limit=100)
nr_uniprot, nr_pdbe, nr_pdb_uniprot, nr_af

WARNING:protein_quest.uniprot:Search for uniprot accessions returned 100 results. There may be more results available, but they are not returned due to the limit of 100. Consider increasing the limit to get more results.
WARNING:protein_quest.uniprot:Search for pdbs on uniprot returned 100 results. There may be more results available, but they are not returned due to the limit of 100. Consider increasing the limit to get more results.
WARNING:protein_quest.uniprot:Search for alphafold entries on uniprot returned 100 results. There may be more results available, but they are not returned due to the limit of 100. Consider increasing the limit to get more results.

(100, 100, 100, 100)

Use [database queries](#query-session-database) to see what was found.

## Fetch structures from PDBe and Alphafold found in Uniprot

In [ ]:
from protein_detective.workflow import async_retrieve_structures

In [ ]:
# Allow asyncio to be nested (needed for jupyter notebooks)
download_path, nr_pdbs, nr_alphafolds = await async_retrieve_structures(session_dir)
download_path, nr_pdbs, nr_alphafolds

Downloading PDBe mmCIF files:   0%|          | 0/100 [00:00<?, ?it/s]

Downloading PDBe mmCIF files: 100%|██████████| 100/100 [00:01<00:00, 80.59it/s]
Fetching Alphafold summaries: 100%|██████████| 100/100 [00:03<00:00, 28.23it/s]
Downloading AlphaFold files: 100%|██████████| 100/100 [00:02<00:00, 49.40it/s]

(PosixPath('session1/downloads'), 100, 100)

## Filter structures

Prepare structures for powerfitting by filtering them based on confidence and nr of residues.

In [4]:
from protein_detective.filter import ConfidenceFilterQuery, FilterOptions, SecondaryStructureFilterQuery
from protein_detective.workflow import filter_structures

In [5]:
options = FilterOptions(
    confidence=ConfidenceFilterQuery(confidence=70, min_residues=100, max_residues=1000),
    secondary_structure=SecondaryStructureFilterQuery(),
)

In [6]:
filtered_dir, filtered_results = filter_structures(session_dir, options)
pprint(filtered_results[:2])
pprint(filtered_results[-2:])
filtered_dir

INFO:distributed.http.proxy:To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
INFO:distributed.scheduler:State start
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/scheduler-bucwcsz7', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-lvlbvbh7', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-limrmyif', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-f69bf2s5', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-20buevia', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-eftwj8al', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-eavah6ta', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/scheduler-xwh_dacg', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-exuu8f8j', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-50j3p894', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/scheduler-0ytcubfp', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-x06v7qpv', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-5p5w_sgr', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-bihfhvhl', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-iurms38z', purging
INFO:distributed.scheduler:  Scheduler at:     tcp://127.0.0.1:42121
INFO:distributed.scheduler:  dashboard at:  http://127.0.0.1:8787/status
INFO:distributed.scheduler:Registering Worker plugin shuffle
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:40077'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:35187'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:42655'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:43557'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:46579'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:46531'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:33095'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:41171'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:46725'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:40283'
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:38499 name: 0
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:38499
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:57034
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:46505 name: 2
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:46505
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:57046
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:43533 name: 3
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:43533
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:57050
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:37583 name: 1
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:37583
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:57070
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:43881 name: 6
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:43881
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:57060
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:43977 name: 7
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:43977
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:57072
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:35033 name: 8
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:35033
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:57086
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:37475 name: 5
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:37475
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:57088
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:42389 name: 4
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:42389
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:57090
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:43717 name: 9
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:43717
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:57106
INFO:distributed.scheduler:Receive client connection: Client-3913c581-9478-11f0-a9c1-39a1d0675eb7
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:57112
INFO:distributed.scheduler:Registering Worker plugin forward-logging-<root>
INFO:distributed.scheduler:Remove client Client-3913c581-9478-11f0-a9c1-39a1d0675eb7
INFO:distributed.core:Received 'close-stream' from tcp://127.0.0.1:57112; closing.
INFO:distributed.scheduler:Remove client Client-3913c581-9478-11f0-a9c1-39a1d0675eb7
INFO:distributed.scheduler:Close client connection: Client-3913c581-9478-11f0-a9c1-39a1d0675eb7

  0%|          | 0/100 [00:00<?, ?file/s]

[
    FilteredStructure(
        uniprot_accession='A0A087WUV0',
        pdb_id=None,
        confidence=ConfidenceFilterResult(
            input_file='AF-A0A087WUV0-F1-model_v4.cif',
            count=283,
            filtered_file=PosixPath('filtered/AF-A0A087WUV0-F1-model_v4.cif')
        ),
        chain=None,
        residue=None,
        secondary_structure=None
    ),
    FilteredStructure(
        uniprot_accession='A0A0C5B5G6',
        pdb_id=None,
        confidence=ConfidenceFilterResult(
            input_file='AF-A0A0C5B5G6-F1-model_v4.cif',
            count=10,
            filtered_file=None
        ),
        chain=None,
        residue=None,
        secondary_structure=None
    )
]

[
    FilteredStructure(
        uniprot_accession='O00482',
        pdb_id='3TX7',
        confidence=None,
        chain=ChainFilterStatistics(
            input_file=PosixPath('session1/downloads/pdbe/3tx7.cif.gz'),
            chain_id='B',
            passed=True,
            output_file=PosixPath('pdb_chain_filtered/3tx7_B2A.cif.gz'),
            discard_reason=None
        ),
        residue=ResidueFilterStatistics(
            input_file=PosixPath('session1/pdb_chain_filtered/3tx7_B2A.cif.gz'),
            residue_count=218,
            passed=True,
            output_file=PosixPath('filtered/3tx7_B2A.cif')
        ),
        secondary_structure=None
    ),
    FilteredStructure(
        uniprot_accession='O00255',
        pdb_id='4GQ3',
        confidence=None,
        chain=ChainFilterStatistics(
            input_file=PosixPath('session1/downloads/pdbe/4gq3.cif.gz'),
            chain_id='A',
            passed=True,
            output_file=PosixPath('pdb_chain_filtered/4gq3_A2A.cif.gz'),
            discard_reason=None
        ),
        residue=ResidueFilterStatistics(
            input_file=PosixPath('session1/pdb_chain_filtered/4gq3_A2A.cif.gz'),
            residue_count=849,
            passed=True,
            output_file=PosixPath('filtered/4gq3_A2A.cif')
        ),
        secondary_structure=None
    )
]

PosixPath('session1/filtered')

INFO:distributed.core:Event loop was unresponsive in Nanny for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.18s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.18s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.18s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.

In [7]:
total_nr = len(filtered_results)
total_nr_passed = sum(1 for r in filtered_results if r.passed)
total_nr_discarded = total_nr - total_nr_passed
pprint(f"Total entries: {total_nr}, passed: {total_nr_passed}, discarded: {total_nr_discarded}")

Total entries: 200, passed: 132, discarded: 68

## Powerfit

In [8]:
from protein_detective.powerfit.options import PowerfitOptions
from protein_detective.powerfit.workflow import powerfit_commands

To run you must have cloned the https://github.com/haddocking/powerfit-tutorial repository in '../../powerfit-tutorial'.

In [9]:
options = PowerfitOptions(
    target=Path("../../powerfit-tutorial/ribosome-KsgA.map"),
    resolution=13,
    angle=20,
    laplace=True,
)

### Run

Here we use printed commands to run powerfit, see [powerfit.ipynb](powerfit.ipynb) for running powerfits using the API.

In [10]:
commands, powerfit_run_id = powerfit_commands(session_dir, options)

In [13]:
powerfit_run_id

1

In [12]:
cwd = str(Path.cwd())
rel_commands = [c.replace(cwd, ".") for c in commands]
pprint(rel_commands[:10])

[
    'powerfit ./session1/powerfit/1/ribosome-KsgA.map 13 ./session1/filtered/AF-A0A087WUV0-F1-model_v4.cif
--laplace --resampling-rate 2 --num 0 --nproc 1 --directory ./session1/powerfit/1/AF-A0A087WUV0-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/1/ribosome-KsgA.map 13 ./session1/filtered/AF-A0A0U1RQI7-F1-model_v4.cif
--laplace --resampling-rate 2 --num 0 --nproc 1 --directory ./session1/powerfit/1/AF-A0A0U1RQI7-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/1/ribosome-KsgA.map 13 ./session1/filtered/AF-A0A1B0GTS1-F1-model_v4.cif
--laplace --resampling-rate 2 --num 0 --nproc 1 --directory ./session1/powerfit/1/AF-A0A1B0GTS1-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/1/ribosome-KsgA.map 13 ./session1/filtered/AF-A0A1B0GWH4-F1-model_v4.cif
--laplace --resampling-rate 2 --num 0 --nproc 1 --directory ./session1/powerfit/1/AF-A0A1B0GWH4-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/1/ribosome-KsgA.map 13 ./session1/filtered/AF-A0A1W2PPF3-F1-model_v4.cif
--laplace --resampling-rate 2 --num 0 --nproc 1 --directory ./session1/powerfit/1/AF-A0A1W2PPF3-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/1/ribosome-KsgA.map 13 ./session1/filtered/AF-A0A1W2PQL4-F1-model_v4.cif
--laplace --resampling-rate 2 --num 0 --nproc 1 --directory ./session1/powerfit/1/AF-A0A1W2PQL4-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/1/ribosome-KsgA.map 13 ./session1/filtered/AF-A1YPR0-F1-model_v4.cif --laplace
--resampling-rate 2 --num 0 --nproc 1 --directory ./session1/powerfit/1/AF-A1YPR0-F1-model_v4 --delimiter , --angle
20',
    'powerfit ./session1/powerfit/1/ribosome-KsgA.map 13 ./session1/filtered/AF-A2RRD8-F1-model_v4.cif --laplace
--resampling-rate 2 --num 0 --nproc 1 --directory ./session1/powerfit/1/AF-A2RRD8-F1-model_v4 --delimiter , --angle
20',
    'powerfit ./session1/powerfit/1/ribosome-KsgA.map 13 ./session1/filtered/AF-A3KN83-F1-model_v4.cif --laplace
--resampling-rate 2 --num 0 --nproc 1 --directory ./session1/powerfit/1/AF-A3KN83-F1-model_v4 --delimiter , --angle
20',
    'powerfit ./session1/powerfit/1/ribosome-KsgA.map 13 ./session1/filtered/AF-A6NDX5-F1-model_v4.cif --laplace
--resampling-rate 2 --num 0 --nproc 1 --directory ./session1/powerfit/1/AF-A6NDX5-F1-model_v4 --delimiter , --angle
20'
]

These commands should be run on a cluster. Here we will just run a couple of them to show how it works.

In [15]:
!{rel_commands[6]}

Target file read from:
/home/stefanv/git/protein-detective/protein-detective/docs/session1/powerfit/1/r
ibosome-KsgA.map
Target resolution: 13.00
Initial shape of density: 128 128 128
Shape after trimming: 60 73 67
Shape after extending: 60 75 70
Template file read from:
/home/stefanv/git/protein-detective/protein-detective/docs/session1/filtered/AF-
A1YPR0-F1-model_v4.cif
Reading in rotations.
Requested rotational sampling density: 20.00
Real rotational sampling density: 20.83
Requested number of processors: 1
Starting search
Processing rotations 100% ━━━━━━━━━━━━ 648/648  [ 0:00:08 < 0:00:00 , 74 rot/s ]t/s ]t/s ]
Time for search: 8.762 s
Analyzing results
Writing solutions to file.
Writing PDBs to file.
Total time: 0m 9s

In [16]:
!{rel_commands[0]}

Target file read from:
/home/stefanv/git/protein-detective/protein-detective/docs/session1/powerfit/1/r
ibosome-KsgA.map
Target resolution: 13.00
Initial shape of density: 128 128 128
Shape after trimming: 60 73 67
Shape after extending: 60 75 70
Template file read from:
/home/stefanv/git/protein-detective/protein-detective/docs/session1/filtered/AF-
A0A087WUV0-F1-model_v4.cif
Reading in rotations.
Requested rotational sampling density: 20.00
Real rotational sampling density: 20.83
Requested number of processors: 1
Starting search
Processing rotations 100% ━━━━━━━━━━━━ 648/648  [ 0:00:08 < 0:00:00 , 72 rot/s ]t/s ]t/s ]
Time for search: 0m 12s
Analyzing results
Writing solutions to file.
Writing PDBs to file.
Total time: 0m 12s

In [13]:
!{rel_commands[-1]}

Target file read from:
/home/stefanv/git/protein-detective/protein-detective/docs/session1/powerfit/1/r
ibosome-KsgA.map
Target resolution: 13.00
Initial shape of density: 128 128 128
Shape after trimming: 60 73 67
Shape after extending: 60 75 70
Template file read from:
/home/stefanv/git/protein-detective/protein-detective/docs/session1/filtered/4gq
3_A2A.cif
Reading in rotations.
Requested rotational sampling density: 20.00
Real rotational sampling density: 20.83
Requested number of processors: 1
Starting search
Processing rotations 100% ━━━━━━━━━━━━ 648/648  [ 0:00:08 < 0:00:00 , 73 rot/s ]t/s ]t/s ]
Time for search: 8.893 s
Analyzing results
Writing solutions to file.
Writing PDBs to file.
Total time: 0m 9s

See [powerfit.ipynb](powerfit.ipynb) for running all powerfits using the API.

### Report

Once all powerfit jobs are done the results can be parsed and reported.

In [ ]:
from protein_detective.powerfit.workflow import powerfit_report

In [ ]:
solutions = powerfit_report(session_dir)

In [ ]:
len(solutions)

4420

In [ ]:
solutions

,powerfit_run_id,structure,rank,cc,fishz,relz,translation,rotation,af_id,pdb_id,pdb_file,uniprot_acc
0,1,O00268_7edx_D2A,1,0.282,0.289,9.595,"[150.43, 150.43, 181.13]","[0.184, 0.816, -0.548, -0.816, -0.184, -0.548,...",None,7EDX,session1/single_chain/O00268_7edx_D2A.pdb,O00268
1,1,O00268_7egf_d2A,1,0.275,0.282,9.141,"[205.69, 217.97, 187.27]","[0.0, 0.604, 0.797, -0.0, -0.797, 0.604, 1.0, ...",None,7EGF,session1/single_chain/O00268_7egf_d2A.pdb,O00268
2,1,O00268_7edx_D2A,2,0.274,0.281,9.329,"[239.46, 153.5, 187.27]","[0.548, -0.184, 0.816, -0.632, 0.548, 0.548, -...",None,7EDX,session1/single_chain/O00268_7edx_D2A.pdb,O00268
3,1,O00268_7edx_D2A,3,0.272,0.279,9.238,"[254.81, 267.09, 178.06]","[0.797, 0.0, -0.604, -0.604, -0.0, -0.797, 0.0...",None,7EDX,session1/single_chain/O00268_7edx_D2A.pdb,O00268
4,1,O00268_7egf_d2A,2,0.269,0.276,8.958,"[196.48, 184.2, 156.57]","[0.0, -0.797, -0.604, 0.0, -0.604, 0.797, -1.0...",None,7EGF,session1/single_chain/O00268_7egf_d2A.pdb,O00268
...,...,...,...,...,...,...,...,...,...,...,...,...
4415,1,AF-O00327-F1-model_v4,1505,0.107,0.108,4.857,"[257.88, 260.95, 168.85]","[-0.362, 0.896, -0.258, 0.896, 0.258, -0.362, ...",O00327,None,session1/density_filtered/AF-O00327-F1-model_v...,O00327
4416,1,AF-O00327-F1-model_v4,1507,0.106,0.106,4.792,"[150.43, 98.24, 193.41]","[0.797, -0.604, 0.0, 0.0, -0.0, 1.0, -0.604, -...",O00327,None,session1/density_filtered/AF-O00327-F1-model_v...,O00327
4417,1,AF-O00327-F1-model_v4,1506,0.106,0.107,4.815,"[214.9, 89.03, 116.66]","[0.0, -0.797, -0.604, 0.0, -0.604, 0.797, -1.0...",O00327,None,session1/density_filtered/AF-O00327-F1-model_v...,O00327
4418,1,AF-O00327-F1-model_v4,1509,0.105,0.106,4.768,"[251.74, 273.23, 122.8]","[-0.258, 0.362, -0.896, -0.362, -0.896, -0.258...",O00327,None,session1/density_filtered/AF-O00327-F1-model_v...,O00327
4419,1,AF-O00327-F1-model_v4,1508,0.105,0.106,4.775,"[233.32, 132.01, 233.32]","[0.604, 0.0, 0.797, -0.797, 0.0, 0.604, 0.0, -...",O00327,None,session1/density_filtered/AF-O00327-F1-model_v...,O00327

### Fit model to solution

Rotate/translate the input model PDB files to the top 5 powerfit solutions.

In [ ]:
from protein_detective.powerfit.workflow import powerfit_fit_models

In [ ]:
fitted = powerfit_fit_models(session_dir, top=5)
fitted

Writing fitted model PDB files: 100%|██████████| 5/5 [00:00<00:00, 128.84it/s]

,powerfit_run_id,structure,rank,fitted_model_file,unfitted_model_file
index,,,,,
0,1,O00268_7edx_D2A,1,session1/powerfit/1/O00268_7edx_D2A/fit_1.pdb,session1/single_chain/O00268_7edx_D2A.pdb
1,1,O00268_7egf_d2A,1,session1/powerfit/1/O00268_7egf_d2A/fit_1.pdb,session1/single_chain/O00268_7egf_d2A.pdb
2,1,O00268_7edx_D2A,2,session1/powerfit/1/O00268_7edx_D2A/fit_2.pdb,session1/single_chain/O00268_7edx_D2A.pdb
3,1,O00268_7edx_D2A,3,session1/powerfit/1/O00268_7edx_D2A/fit_3.pdb,session1/single_chain/O00268_7edx_D2A.pdb
4,1,O00268_7egf_d2A,2,session1/powerfit/1/O00268_7egf_d2A/fit_2.pdb,session1/single_chain/O00268_7egf_d2A.pdb